"""Shared defaults for route measurement runners."""

DEFAULT_CONTACT_SETTLE_S = 0.2
SHORT_CHECK_SAMPLE_COUNT = 10
AUTO_CONTACT_SEEK_STEP_MM = -0.001
AUTO_CONTACT_SEEK_MAX_TOTAL_MM = 0.010

__all__ = [
    "AUTO_CONTACT_SEEK_MAX_TOTAL_MM",
    "AUTO_CONTACT_SEEK_STEP_MM",
    "DEFAULT_CONTACT_SETTLE_S",
    "SHORT_CHECK_SAMPLE_COUNT",
]
