"""Default values used by route measurement dialog controls and profiles."""

from __future__ import annotations

from probe_station_gui.route.measurement import RouteContactQualityLimits


ROUTE_MEASUREMENT_PROFILE_VERSION = 7
KEITHLEY_DEFAULTS_PROFILE_VERSION = 6
DEFAULT_ROUTE_INITIAL_MEASUREMENT_COUNT = 10
DEFAULT_ROUTE_FOLLOWUP_MEASUREMENT_COUNT = 240
DEFAULT_ROUTE_PHOTO_AUTOFOCUS_RANGE_MM = 0.030
DEFAULT_KEITHLEY_MEASUREMENT_VOLTAGE_V = 0.03
DEFAULT_KEITHLEY_SOURCE_RANGE_V = 0.21
DEFAULT_KEITHLEY_VOLTMETER_RANGE_V = 0.1
DEFAULT_KEITHLEY_CURRENT_RANGE_A = 10e-6
DEFAULT_KEITHLEY_COMPLIANCE_CURRENT_A = 10e-6
DEFAULT_KEITHLEY_NPLC = 1.0
DEFAULT_KEITHLEY_TRIGGER_DELAY_S = 0.0
DEFAULT_KEITHLEY_USE_BUFFER = True
DEFAULT_KEITHLEY_USE_TRIGGER_LINK = True
DEFAULT_ROUTE_CONTACT_SEEK_RANGE_MM = 0.010
DEFAULT_ROUTE_CONTACT_SEEK_STEP_MM = 0.001
DEFAULT_ROUTE_CONTACT_QUALITY_LIMITS = RouteContactQualityLimits()

VOLTAGE_PREFIXES = (
    ("uV", 1e-6),
    ("mV", 1e-3),
    ("V", 1.0),
)
CURRENT_PREFIXES = (
    ("uA", 1e-6),
    ("mA", 1e-3),
    ("A", 1.0),
)
RESISTANCE_PREFIXES = (
    ("mohm", 1e-3),
    ("ohm", 1.0),
    ("kohm", 1e3),
    ("Mohm", 1e6),
    ("Gohm", 1e9),
)
FREQUENCY_PREFIXES = (
    ("Hz", 1.0),
    ("kHz", 1e3),
)
